--------------- USERS ---------------
CREATE TABLE users
(
    id    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name  VARCHAR(250)                            NOT NULL,
    email VARCHAR(254)                            NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_74165e195b2f7b25de690d14a UNIQUE (email);


--------------- CATEGORIES ---------------
CREATE TABLE categories
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(50)                             NOT NULL,
    CONSTRAINT pk_categories PRIMARY KEY (id)
);

ALTER TABLE categories
    ADD CONSTRAINT uc_8c269303ee284e8482d8b499d UNIQUE (name);


--------------- COMPILATIONS ---------------
CREATE TABLE compilations
(
    id     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title  VARCHAR(50)                             NOT NULL,
    pinned BOOLEAN,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);


--------------- EVENTS ---------------
CREATE TABLE events
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation         TEXT                                    NOT NULL,
    category_id        BIGINT                                  NOT NULL,
    confirmed_requests BIGINT,
    created_on         TIMESTAMP WITHOUT TIME ZONE,
    description        TEXT,
    event_date         TIMESTAMP(0) WITHOUT TIME ZONE          NOT NULL,
    initiator_id       BIGINT                                  NOT NULL,
    paid               BOOLEAN                                 NOT NULL,
    participant_limit  BIGINT,
    published_on       TIMESTAMP(0) WITHOUT TIME ZONE,
    request_moderation BOOLEAN,
    state              VARCHAR(255),
    title              VARCHAR(255)                            NOT NULL,
    lat                FLOAT,
    lon                FLOAT,
    CONSTRAINT pk_events PRIMARY KEY (id)
);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_CATEGORY FOREIGN KEY (category_id) REFERENCES categories (id);

ALTER TABLE events
    ADD CONSTRAINT FK_EVENTS_ON_INITIATOR FOREIGN KEY (initiator_id) REFERENCES users (id);

--------------- COMPILATION-EVENTS ---------------
CREATE TABLE compilation_events
(
    compilation_id BIGINT NOT NULL,
    event_id       BIGINT NOT NULL,
    CONSTRAINT pk_compilation_events PRIMARY KEY (compilation_id, event_id)
);

ALTER TABLE compilation_events
    ADD CONSTRAINT fk_comeve_on_compilation_entity FOREIGN KEY (compilation_id) REFERENCES compilations (id);

ALTER TABLE compilation_events
    ADD CONSTRAINT fk_comeve_on_event_entity FOREIGN KEY (event_id) REFERENCES events (id);


--------------- REQUESTS ---------------
CREATE TABLE event_requests
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    requester_id BIGINT                                  NOT NULL,
    event_id     BIGINT                                  NOT NULL,
    status       VARCHAR(255)                            NOT NULL,
    created      TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_event_requests PRIMARY KEY (id)
);

ALTER TABLE event_requests
    ADD CONSTRAINT FK_EVENT_REQUESTS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

ALTER TABLE event_requests
    ADD CONSTRAINT FK_EVENT_REQUESTS_ON_REQUESTER FOREIGN KEY (requester_id) REFERENCES users (id);


--------------- COMMENTS ---------------
CREATE TABLE comments
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text       TEXT                                    NOT NULL,
    author_id  BIGINT                                  NOT NULL,
    event_id   BIGINT                                  NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id)
);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES users (id);

ALTER TABLE comments
    ADD CONSTRAINT FK_COMMENTS_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (id);

